<!-- src/routes/traffic-engineering/traffic-assessment/+page.svelte -->
<script>
	import { locale } from 'svelte-i18n';
	import ServicePageLayout from '$lib/components/ServicePageLayout.svelte';
	import { BarChart3, Search, TrendingUp, MapPin, Clock, Shield, Target, FileCheck } from 'lucide-svelte';
  
	const features = [
		{
			icon: BarChart3,
			title: "تقييم تأثير المرور",
			titleEn: "Traffic Impact Assessment",
			description: "تحليل شامل لتأثير التطويرات الجديدة على شبكة المرور الحالية مع تحديد التأثيرات والحلول المناسبة",
			descriptionEn: "Comprehensive analysis of new development impacts on existing traffic network with impact identification and appropriate solutions"
		},
		{
			icon: Search,
			title: "دراسة الوضع المروري الحالي",
			titleEn: "Existing Traffic Condition Study",
			description: "تحليل مفصل للظروف المرورية الحالية بما في ذلك أحجام المرور وأنماط الحركة ومستويات الخدمة",
			descriptionEn: "Detailed analysis of current traffic conditions including traffic volumes, movement patterns, and service levels"
		},
		{
			icon: TrendingUp,
			title: "توقع المرور المستقبلي",
			titleEn: "Future Traffic Forecasting",
			description: "توقع أحجام المرور المستقبلية باستخدام أحدث النماذج والطرق الإحصائية المعتمدة دولياً",
			descriptionEn: "Forecasting future traffic volumes using latest models and internationally approved statistical methods"
		},
		{
			icon: MapPin,
			title: "تحليل توليد الرحلات",
			titleEn: "Trip Generation Analysis",
			description: "حساب دقيق لعدد الرحلات التي ستولدها التطويرات المختلفة بناءً على نوع الاستخدام والحجم",
			descriptionEn: "Accurate calculation of trips generated by different developments based on land use type and size"
		},
		{
			icon: Clock,
			title: "تحليل الذروة المرورية",
			titleEn: "Peak Hour Analysis",
			description: "دراسة مفصلة لفترات الذروة المرورية وتوزيع الأحجام على مدار اليوم والأسبوع",
			descriptionEn: "Detailed study of traffic peak periods and volume distribution throughout day and week"
		},
		{
			icon: Shield,
			title: "تقييم السلامة المرورية",
			titleEn: "Traffic Safety Assessment",
			description: "تحليل المخاطر المرورية المحتملة وتقييم مستوى السلامة مع اقتراح التحسينات اللازمة",
			descriptionEn: "Analysis of potential traffic risks and safety level evaluation with necessary improvement recommendations"
		},
		{
			icon: Target,
			title: "تحليل القدرة الاستيعابية",
			titleEn: "Capacity Analysis",
			description: "تقييم القدرة الاستيعابية للطرق والتقاطعات ومستوى الخدمة في ظل الظروف المختلفة",
			descriptionEn: "Evaluation of road and intersection capacity and service levels under different conditions"
		},
		{
			icon: FileCheck,
			title: "تدابير التخفيف والحلول",
			titleEn: "Mitigation Measures and Solutions",
			description: "تطوير تدابير التخفيف المناسبة والحلول المرورية لمعالجة التأثيرات السلبية المحددة",
			descriptionEn: "Development of appropriate mitigation measures and traffic solutions to address identified negative impacts"
		}
	];
  
	const benefits = [
		{
			text: "ضمان الامتثال للمتطلبات التنظيمية والتخطيطية",
			textEn: "Ensuring compliance with regulatory and planning requirements"
		},
		{
			text: "تحديد التأثيرات المرورية قبل التنفيذ",
			textEn: "Identifying traffic impacts before implementation"
		},
		{
			text: "تطوير حلول فعالة لمشاكل المرور المحتملة",
			textEn: "Developing effective solutions for potential traffic problems"
		},
		{
			text: "دعم اتخاذ القرارات التخطيطية المدروسة",
			textEn: "Supporting informed planning decision-making"
		},
		{
			text: "تحسين السلامة المرورية والكفاءة التشغيلية",
			textEn: "Improving traffic safety and operational efficiency"
		},
		{
			text: "تقليل المخاطر القانونية والمالية للمطورين",
			textEn: "Reducing legal and financial risks for developers"
		},
		{
			text: "تحسين جودة الحياة في المناطق المجاورة",
			textEn: "Improving quality of life in adjacent areas"
		},
		{
			text: "توفير أساس علمي لطلبات التمويل والموافقات",
			textEn: "Providing scientific basis for funding and approval applications"
		}
	];
  
	const process = [
		{
			title: "جمع البيانات الأساسية",
			titleEn: "Baseline Data Collection",
			description: "جمع شامل للبيانات المرورية الحالية والمعلومات الديموغرافية والتخطيطية ذات الصلة",
			descriptionEn: "Comprehensive collection of current traffic data and relevant demographic and planning information"
		},
		{
			title: "التحليل والنمذجة",
			titleEn: "Analysis and Modeling",
			description: "تحليل البيانات وتطوير النماذج المرورية لفهم الظروف الحالية والمستقبلية",
			descriptionEn: "Data analysis and traffic model development to understand current and future conditions"
		},
		{
			title: "تقييم التأثيرات",
			titleEn: "Impact Assessment",
			description: "تقييم التأثيرات المرورية المحتملة وتحديد المناطق التي تحتاج إلى اهتمام خاص",
			descriptionEn: "Assessment of potential traffic impacts and identification of areas requiring special attention"
		},
		{
			title: "التوصيات والحلول",
			titleEn: "Recommendations and Solutions",
			description: "تطوير التوصيات والحلول المناسبة مع إعداد التقارير التفصيلية والعروض التقديمية",
			descriptionEn: "Development of appropriate recommendations and solutions with detailed reports and presentations"
		}
	];
  
	const caseStudies = [
		{
			title: "تقييم مرور المجمع التجاري",
			titleEn: "Commercial Complex Traffic Assessment",
			description: "دراسة تأثير مجمع تجاري كبير بمساحة 80,000 م² على شبكة المرور المحيطة مع حلول التخفيف",
			descriptionEn: "Impact study of large 80,000 m² commercial complex on surrounding traffic network with mitigation solutions",
			location: "المنطقة التجارية الجديدة",
			locationEn: "New Commercial District",
			duration: "4 أشهر",
			durationEn: "4 months",
			team: "7 متخصصين",
			teamEn: "7 specialists"
		},
		{
			title: "تقييم المجتمع السكني الكبير",
			titleEn: "Large Residential Community Assessment",
			description: "تحليل تأثير مجتمع سكني من 2000 وحدة على الطرق المحلية مع تحسينات البنية التحتية",
			descriptionEn: "Impact analysis of 2000-unit residential community on local roads with infrastructure improvements",
			location: "الضاحية الجنوبية",
			locationEn: "Southern Suburb",
			duration: "5 أشهر",
			durationEn: "5 months",
			team: "6 متخصصين",
			teamEn: "6 specialists"
		},
		{
			title: "تقييم الحرم الجامعي",
			titleEn: "University Campus Assessment",
			description: "دراسة شاملة للتأثير المروري لحرم جامعي جديد يستوعب 20,000 طالب مع نظام نقل متكامل",
			descriptionEn: "Comprehensive traffic impact study for new university campus accommodating 20,000 students with integrated transport system",
			location: "الحرم الجامعي الشرقي",
			locationEn: "Eastern University Campus",
			duration: "8 أشهر",
			durationEn: "8 months",
			team: "10 متخصصين",
			teamEn: "10 specialists"
		}
	];
  
	const stats = [
		{
			value: "300+",
			label: "تقييم مروري مكتمل",
			labelEn: "Traffic Assessments Completed"
		},
		{
			value: "92%",
			label: "معدل قبول التوصيات",
			labelEn: "Recommendation Acceptance Rate"
		},
		{
			value: "45",
			label: "يوم متوسط التسليم",
			labelEn: "Days Average Delivery"
		},
		{
			value: "98%",
			label: "دقة التوقعات",
			labelEn: "Forecast Accuracy"
		}
	];
</script>

<ServicePageLayout
	title={($locale || 'en') === 'ar' ? 'تقييم المرور' : 'Traffic Assessment'}
	subtitle={($locale || 'en') === 'ar' ? 'تحليل شامل لتأثيرات المرور والحلول المناسبة' : 'Comprehensive analysis of traffic impacts and appropriate solutions'}
	description={($locale || 'en') === 'ar' ? 'خدمات تقييم المرور المتخصصة لتحليل تأثير التطويرات على شبكات المرور الحالية مع تطوير الحلول والتدابير المناسبة لضمان كفاءة وسلامة النظام المروري وتلبية المتطلبات التنظيمية' : 'Specialized traffic assessment services analyzing development impacts on existing traffic networks while developing appropriate solutions and measures to ensure traffic system efficiency, safety, and regulatory compliance'}
	icon="📈"
	{features}
	{benefits}
	{process}
	{caseStudies}
	{stats}
/>